kind: ConfigMap
apiVersion: v1
metadata:
  name: labldap-ldap-ca
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEhTCCAu2gAwIBAgIBATANBgkqhkiG9w0BAQsFADA0MRIwEAYDVQQKDAlLRU1P
    LkxBQlMxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMTA0MDUx
    NjI1MTVaFw00MTA0MDUxNjI1MTVaMDQxEjAQBgNVBAoMCUtFTU8uTEFCUzEeMBwG
    A1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0BAQEFAAOC
    AY8AMIIBigKCAYEAxGlVOZnaUfuUgSWNcgxYn3Nrj/QaDyICI5R6D+ihruRzz/Uh
    TKOf17eU87Vd+q1SDZkB34tD/Y80XN90aCfUhzctl5f+mX2UK27eiRtALtD7uPKR
    iRKW2TqOgqk7UQt0qALZhBYtbOkL+AfekFgiWX0ni3NeBp9Rn2254Qk2rE4bfwPv
    e9HqRLyjsotg9N//3g2FYrqxhxItluuSiyiy/mcYugIMEtnZgeKNW4id+9GXfIlA
    yuxP5iff3SHjKSJl2wBpK/mjZHgyR69qVa1pHxvNwxygGFxbji8WV3S4C/Qc+FL4
    vmqp0CSIBXYdRiABxXtuSkhuFrXpr6PuCpVCOlg1vY+3IGxkkTjUFpXyfcZ6yC3l
    E1Ahna7lHYc3E0aLep09WmRsM0v3ghrHbVLZkZwq/l+A6pFUhnytRyrOJswFoOps
    2Xe/E32ppslcP198CfpcwGGQpOMFkRcpBy8YebnP4iac10IRVOVzmR0G5Fh8GaLR
    KcANWWIk2eWonLZ7AgMBAAGjgaEwgZ4wHwYDVR0jBBgwFoAUMOZ7r6nu7AJpozoz
    jH0Od3n+yuUwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwHQYDVR0O
    BBYEFDDme6+p7uwCaaM6M4x9Dnd5/srlMDsGCCsGAQUFBwEBBC8wLTArBggrBgEF
    BQcwAYYfaHR0cDovL2lwYS1jYS5rZW1vLmxhYnMvY2Evb2NzcDANBgkqhkiG9w0B
    AQsFAAOCAYEAEZNOmzJ1jepOY6ErLPvp9h15wjvqjw0dFwtKGN8y9uBGRe5rk6W7
    2+rBhl81Ldda3zrDzfJpL3ZDf70ABntw8s2T30xkg0XH+Rp5mUrVRKIrAXqOv55p
    ZX5tUthNsLFtyMChH6RUsjqEJE+F1q7quqHuaM2bAcTsDI/lFqqSc1q8jTk8X4gY
    isBayasMYVp8EgPMDDgJ2HLTXz1zO2tW8kcyoULTK4/V49XqhP3h8lcPEDUUxds2
    OKVWKvDQoJjQyNyvEd4nwZZeHNAzgIOEVbjLrUv9Orm2I3HnSLrLmbiC5pc+D+Zp
    IEwDTEuww/c6d5eOC27RoGXXa10jBECcWFJZKv6DxGd7Zct7/Anb9CrllLzBhmr5
    AieIGxT+6B1bEF/lvVq3uijHFv+BB0gA9wf0lmMJqRgXNC2tO96DRztgSTthGiHG
    iJfPVmjFvdy+DQ1CjvRs2VBsqhQzovBW5cvqnbQcOZDg7UJz055df1w21QMTxSlt
    3b0/ztTURpAx
    -----END CERTIFICATE-----
