---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: hive-cluster-admin
subjects:
  - kind: ServiceAccount
    name: hiveadmission
    namespace: hive
  - kind: ServiceAccount
    name: hive-controllers
    namespace: hive
  - kind: ServiceAccount
    name: hive-frontend
    namespace: hive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin