---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00_namespace.yml
  - 07_operatorgroup.yml
  - 10_subscription.yml
#patchesStrategicMerge:
#- operator-nodeselectors.yml
