apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gitea-operator.openshift-operators: ''
  name: gitea-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: kenmoini-gitea
  sourceNamespace: openshift-marketplace