apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: install-rhacm-operator
  namespace: openshift-gitops
spec:
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
    - group: "v1"
      kind: "Namespace"
      jsonPointers:
        - /metadata/labels
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    kustomize:
      version: v4.4.1
    repoURL: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: manifests/install-rhacm-operator
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    #directory:
    #  recurse: true
  project: hub-of-hubs-cluster-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state