# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   labels:
#     operators.coreos.com/advanced-cluster-management.open-cluster-management: ''
#   name: advanced-cluster-management
#   namespace: open-cluster-management
# spec:
#   config:
#     nodeSelector:
#       node-role.kubernetes.io/infra: ""
#     tolerations:
#     - effect: NoSchedule
#       key: node.ocs.openshift.io/storage
#       operator: Equal
#       value: 'true'
#     - effect: NoSchedule
#       key: node-role.kubernetes.io/infra
#       operator: Equal
#       value: "reserved"
#     - effect: NoExecute
#       key: node-role.kubernetes.io/infra
#       operator: Equal
#       value: "reserved"
