---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy-rhacm-hub
- external-secrets
- hoh-rhacm-base-config
- install-rhacm-operator
- reflector-chart-installed
- rhacm-applications
- rhacm-channels
#- rhacm-observability
- rhacm-policies
- sealedsecrets-chart-installed